config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|ja/ do
    resources :books, :reports do
      resources :comments
    end

    devise_for :users, skip: :omniauth_callback, controllers: {
        registrations: "users/registrations",
        sessions: "users/sessions",
    }
    resources :users, only: [:index, :show] do
      member do
        resources :following, only: [:index]
        resources :followers, only: [:index]
      end
    end
    resources :follows, only: [:create, :destroy]
    resources :comments
  end
  root to: "books#index"
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :omniauthable

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.name = auth.info.name
      user.email = auth.info.email
      user.password = Devise.friendly_token[6, 20]
    end
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    active_follows.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  validates :name, presence: true
  validates :email, presence: true
  validates :password, confirmation: true

  has_many :books,
           foreign_key: "user_id",
           dependent: :destroy
  has_many :reports,
           foreign_key: "user_id",
           dependent: :destroy
  has_one_attached :icon
  has_many :active_follows, class_name: "Follow",
           foreign_key: "follower_id",
           dependent: :destroy
  has_many :passive_follows, class_name: "Follow",
           foreign_key: "followed_id",
           dependent: :destroy
  has_many :following, through: :active_follows, source: :followed
  has_many :followers, through: :passive_follows, source: :follower
  has_many :comments, foreign_key: "user_id", dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def github
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      set_flash_message(:notice, :success, kind: :"Github",) if is_navigational_format?
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end
  # If you have extra params to permit, append them to the sanitizer.
  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    user_path(id: current_user.id)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def index
    @users = User.page params[:page]
  end

  def show
    @user = User.find(params[:id])
    @posts = Book.where(user_id: @user) + Report.where(user_id: @user)
    @posts.sort_by! { |post| post[:created_at] }
  end
end

app/views/users/_stats.html.slim
- @user ||= current_user

= link_to "following", following_user_path(@user)
= @user.following.count
'|
= link_to "followers", followers_user_path(@user)
= @user.followers.count

app/views/users/index.html.slim
h1 = t('title.all_users')
.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name(:icon)
      th = User.human_attribute_name(:name)
  tbody
  - @users.each do |user|
    tr
      td = image_tag user.icon.variant(resize: "100x100").processed if user.icon.attached?
      td = link_to user.name, user
.mt-3
  = paginate @users
  = page_entries_info @users

app/views/users/show.html.slim
h1 = t('title.profile')

table.table.table-hover
  tbody
    tr
      th = User.human_attribute_name(:icon)
      td = image_tag @user.icon.variant(resize: "100x100").processed if @user.icon.attached?
    tr
      th = User.human_attribute_name(:name)
      td = @user.name
    tr
      th = User.human_attribute_name(:email)
      td = @user.email
    tr
      th = User.human_attribute_name(:postal_code)
      td = @user.postal_code
    tr
      th = User.human_attribute_name(:address)
      td = @user.address
    tr
      th = User.human_attribute_name(:profile)
      td = @user.profile
    tr
      th = User.human_attribute_name(:following)
      td = link_to @user.following.count, following_index_path
    tr
      th = User.human_attribute_name(:followers)
      td = link_to @user.followers.count, followers_path

- if current_user != User.find(params[:id])
  p = render 'follow_form'

.mt-5
  - if current_user == @user
    = link_to t('link.new_book'), new_book_path, class: 'btn btn-primary mr-3'
    = link_to t('link.new_report'), new_report_path, class: 'btn btn-primary mr-3'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = t('activerecord.attributes.post.category')
      th = t('activerecord.attributes.book.created_user')
      th = t('activerecord.attributes.post.title')
      th colspan='4'

  tbody
    - @posts.each do |post|
      tr
        td = post.class
        td = link_to post.user.name ,user_path(post.user)
        td = post.title
        td = link_to t('link.show'), post