config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|ja/ do
    resources :books, :reports do
      resources :comments
    end

    devise_for :users, skip: :omniauth_callback, controllers: {
        registrations: "users/registrations",
        sessions: "users/sessions",
    }
    resources :users, only: [:index, :show] do
      member do
        resources :following, only: [:index]
        resources :followers, only: [:index]
      end
    end
    resources :follows, only: [:create, :destroy]
    resources :comments
  end
  root to: "books#index"
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  mount_uploader :picture, PictureUploader

  validates :title, presence: true

  belongs_to :user
  has_many :comments, as: :commentable,
           dependent: :destroy
end

app/controllers/books_controller.rb
# frozen_string_literal: true

class BooksController < ApplicationController
  before_action :set_created_book, only: [:edit, :update, :destroy]

  def index
    following_users = current_user.following
    @books = Book.where(user_id: following_users).or(Book.where(user_id: current_user)).order(created_at: :desc).page params[:page]
  end

  def new
    @book = Book.new
  end

  def show
    @book = Book.find_by(id: params[:id])
    @comments = @book.comments
    @comment = Comment.new
  end

  def edit
  end

  def create
    @book = Book.new(book_params.merge(user_id: current_user.id))

    if @book.save
      redirect_to @book, notice: t("successfully.Book_was_successfully_created.")
    else
      render :new, notice: t("errors.messages.Book_was_failuer_created.")
    end
  end

  def update
    if @book.update(book_params)
      redirect_to @book, notice: t("successfully.Book_was_successfully_updated.")
    else
      render :edit, notice: t("errors.messages.Book_was_failuer_updated.")
    end
  end

  def destroy
    if @book.destroy
      redirect_to books_url, notice: t("successfully.Book_was_successfully_destroyed.")
    else
      redirect_to @book, notice: t("errors.messages.Book_was_failuer_destroyed.")
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_created_book
    @book = Book.find_by(id: params[:id], user_id: current_user)
  end

  def book_params
    params.require(:book).permit(:title, :memo, :author, :picture, :user_id)
  end
end

app/views/books/_form.html.slim
= form_with(model: @book, local: true) do |form|

  = render "error_template_header", model: @book

  .form-group
    = form.label :title
    = form.text_field :title, class: 'form-control'

  .form-group
    = form.label :memo
    = form.text_area :memo, class: 'form-control'

  .form-group
    = form.label :author
    = form.text_field :author, class: 'form-control'

  .form-group
    = form.label :picture
    div
    = form.file_field :picture

  .actions
    = form.submit nil, class: 'btn btn-primary mr-3'

app/views/books/edit.html.slim
h1 = t'title.editing_book'

= render 'form', book: @book

= link_to t('link.show'), @book
'|
= link_to t('link.back'), books_path

app/views/books/index.html.slim
= render "books_list", books: @books

.mt-5
  = link_to t('link.new_book'), new_book_path, class: 'btn btn-primary mr-3'

app/views/books/new.html.slim
h1 = t'title.new_book'

= render 'form', book: @book

.nav.justify-content-end
  = link_to t('link.back'), books_path

app/views/books/show.html.slim
h1 = t('title.books_detail')

table.table.table-hover
  tbody
    tr
      th = Book.human_attribute_name(:created_user)
      td = link_to @book.user.name, user_path(@book.user_id)
    tr
      th = Book.human_attribute_name(:title)
      td = @book.title
    tr
      th = Book.human_attribute_name(:memo)
      td = @book.memo
    tr
      th = Book.human_attribute_name(:author)
      td = @book.author
    tr
      th = Book.human_attribute_name(:picture)
      td = image_tag(@book.picture_url) if @book.picture.present?

= link_to t('link.edit'), edit_book_path(@book), class: 'btn btn-primary mr-3'

= link_to t('link.back'), books_path, class: 'btn btn-primary mr-3'

= render "comments_list", comments: @book.comments

= render "comment_form", commentable: @book, comment: Comment.new