config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|ja/ do
    resources :books, :reports do
      resources :comments
    end

    devise_for :users, skip: :omniauth_callback, controllers: {
        registrations: "users/registrations",
        sessions: "users/sessions",
    }
    resources :users, only: [:index, :show] do
      member do
        resources :following, only: [:index]
        resources :followers, only: [:index]
      end
    end
    resources :follows, only: [:create, :destroy]
    resources :comments
  end
  root to: "books#index"
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:icon, :name, :postal_code, :address, :profile, :password, :password_confirmation])
    devise_parameter_sanitizer.permit(:account_update, keys: [:icon, :name, :postal_code, :address, :profile, :password, :password_confirmation])
  end

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options
    {locale: I18n.locale}
  end
end

app/views/application/_books_list.html.slim
h1 = t 'title.books'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = Book.human_attribute_name(:created_user)
      th = Book.human_attribute_name(:title)
      th = Book.human_attribute_name(:author)
      th = Book.human_attribute_name(:picture)
      th colspan='4'

  tbody
    - books.each do |book|
      tr
        td = link_to book.user.name ,user_path(book.user_id)
        td = book.title
        td = book.author
        td = image_tag(book.picture_url) if book.picture.present?
        td = link_to t('link.show'), book
        / 改善点：同じif文を2回使っている
        td = link_to t('link.edit'), edit_book_path(book) if current_user == book.user
        td = link_to t('link.destroy'), book, method: :delete, data: {confirm: t('helpers.submit.are_you_sure')} if current_user == book.user

.mt-3
  = paginate books
  = page_entries_info books

app/views/application/_comment_form.html.slim
= form_with(model: [commentable, comment], local: true) do |form|

  = render "error_template_header", model: comment

  .form-group
    = form.text_area :text, class: 'form-control'

    = form.hidden_field :commentable_type, value: commentable.class
    = form.hidden_field :commentable_id, value: commentable.id
    = form.hidden_field :user_id, value: current_user.id

  .actions
    = form.submit t('activerecord.attributes.comment.post_comment'), class: 'btn btn-primary mr-3'

app/views/application/_comments_list.html.slim
.mt-5
table.table.table-hover
  thead.thead-default
    tr
      th = Comment.human_attribute_name(:posted_user)
      th = Comment.human_attribute_name(:comment)
      th colspan='2'
  tbody
    - unless comments.nil?
      - comments.each do |comment|
        tr
          td = link_to comment.user.name, user_path
          td = comment.text
          td = link_to t("link.edit"), edit_comment_path(comment) if current_user == comment.user
          td = link_to t("link.destroy"), comment, method: :delete, data: {confirm: t('helpers.submit.are_you_sure')} if current_user == comment.user

app/views/application/_error_template_header.html.slim
- if model.errors.any?
  div#error_explanation
    h2 = t "activerecord.errors.template.header.other", model: model.class, count: model.errors.count

    ul
      - model.errors.full_messages.each do |message|
        li = message

app/views/application/_follow_button.html.slim
= form_for(current_user.active_follows.build) do |f|
  = hidden_field_tag :followed_id, @user.id
  = f.submit t('button.follow'), class: "btn btn-primary"

app/views/application/_follow_form.html.slim
#follow_form
  - if current_user.following?(@user)
    = render 'unfollow_button'
  - else
    = render 'follow_button'

app/views/application/_show_follow.html.slim
h1 = title

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = User.human_attribute_name(:icon)
      th = User.human_attribute_name(:name)
  tbody
  - @users.each do |user|
    tr
      td = image_tag user.icon.variant(resize: "100x100").processed if user.icon.attached?
      td = link_to user.name, user

.mt-3
  = paginate @users
  = page_entries_info @users

app/views/application/_unfollow_button.html.slim
= form_for(current_user.active_follows.find_by(followed_id: @user.id), html: {method: :delete}) do |f|
  = f.submit t('button.unfollow'), class: "btn btn-primary"