config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: {
      omniauth_callbacks: "users/omniauth_callbacks"
  }

  scope "(:locale)", locale: /en|ja/ do
    resources :books, :reports do
      resources :comments
    end

    devise_for :users, skip: :omniauth_callback, controllers: {
        registrations: "users/registrations",
        sessions: "users/sessions",
    }
    resources :users, only: [:index, :show] do
      member do
        resources :following, only: [:index]
        resources :followers, only: [:index]
      end
    end
    resources :follows, only: [:create, :destroy]
    resources :comments
  end
  root to: "books#index"
end

app/models/report.rb
# frozen_string_literal: true

class Report < ApplicationRecord
  belongs_to :user
  has_many_attached :pictures
  validates :title, presence: true
  has_many :comments, as: :commentable,
           dependent: :destroy
end

app/controllers/reports_controller.rb
# frozen_string_literal: true

class ReportsController < ApplicationController
  before_action :set_created_report, only: [:edit, :update, :destroy]

  def index
    following_users = current_user.following
    @reports = Report.where(user_id: following_users).or(Report.where(user_id: current_user)).order(created_at: :DESC).page params[:page]
  end

  def show
    @report = Report.find_by(id: params[:id])
    @comments = @report.comments
    @comment = Comment.new
  end

  def new
    @report = Report.new
  end

  def edit
  end

  def create
    @report = Report.new(report_params.merge(user_id: current_user.id))
    if @report.save
      redirect_to @report, notice: t("successfully.Report_was_successfully_created.")
    else
      render :new, notice: t("errors.messages.Report_was_failuer_created.")
    end
  end

  def update
    if @report.update(report_params)
      redirect_to @report, notice: t("successfully.Report_was_successfully_updated.")
    else
      render :edit, notice: t("errors.messages.Report_was_failuer_updated.")
    end
  end

  def destroy
    if @report.destroy
      redirect_to reports_path, notice: t("successfully.Report_was_successfully_destroyed.")
    else
      redirect_to @report, notice: t("errors.messages.Report_was_failuer_destroyed.")
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_created_report
    @report = Report.find_by(id: params[:id], user_id: current_user)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def report_params
    params.require(:report).permit(:title, :text, :user_id, pictures: [])
  end
end

app/views/reports/_form.html.slim
= form_with(model: @report, local: true) do |form|

  = render "error_template_header", model: @report

  .form-group
    = form.label :title
    = form.text_field :title, class: 'form-control'

  .form-group
    = form.label :text
    = form.text_area :text, class: 'form-control'

  .form-group
    = form.label :pictures
    div
    = form.file_field :pictures, multiple: true

  .actions
    = form.submit nil, class: 'btn btn-primary mr-3'

app/views/reports/edit.html.slim
h1 = t('title.edit_report')

= render 'form'

= link_to t('link.show'), @report
'|
= link_to t('link.back'), reports_path

app/views/reports/index.html.slim
h1 = t('title.reports')

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th = Report.human_attribute_name(:created_user)
      th = Report.human_attribute_name(:title)
      th colspan='3'

  tbody
    - @reports.each do |report|
      tr
        td = link_to report.user.name ,user_path(report.user_id)
        td = report.title
        td = link_to t('link.show'), report
        / 改善点：同じif文を2回使っている
        td = link_to t('link.edit'), edit_report_path(report) if current_user == report.user
        td = link_to t('link.destroy'), report, method: :delete, data: {confirm: t('helpers.submit.are_you_sure')} if current_user == report.user

.mt-3
  = paginate @reports
  = page_entries_info @reports

.mt-5
  = link_to t('link.new_report'), new_report_path, class: 'btn btn-primary mr-3'

app/views/reports/new.html.slim
h1 = t('title.new_report')

= render "form"

.nav.justify-content-end
  = link_to t('link.back'), reports_path

app/views/reports/show.html.slim
h1 = t('title.report_detail')

table.table.table-hover
  tbody
    tr
      th = Report.human_attribute_name(:created_user)
      td = link_to @report.user.name, user_path(@report.user_id)
    tr
      th = Report.human_attribute_name(:title)
      td = @report.title
    tr
      th = Report.human_attribute_name(:text)
      td = @report.text
    tr
      th = Report.human_attribute_name(:pictures)
      td
        - @report.pictures.each do |picture|
          = image_tag picture if @report.pictures.attached?

= link_to t('link.edit'), edit_report_path(@report), class: 'btn btn-primary mr-3'

= link_to t('link.back'), reports_path, class: 'btn btn-primary mr-3'

= render "comments_list", comments: @report.comments

= render "comment_form", commentable: @report, comment: Comment.new